### ISSUE TITLE
怎么实现定时呢？

### ISSUE THREAD

**Issue by leekaka** [chenjiandongx/email-subscribe#3]
![image](https://user-images.githubusercontent.com/29266786/45364179-071cf080-b60c-11e8-88c8-a5454860e701.png)

**Comment by leekaka** [comment]
我需要这样才能发送

**Comment by chenjiandongx** [comment]
使用 travis，travis 有每日任务，本来 travis 是用来跑测试的，可以定期跑。顺便也就当做免费服务器啦。

**Comment by chenjiandongx** [comment]
具体在这里 https://docs.travis-ci.com/user/cron-jobs/
