### ISSUE TITLE
我想问下这个sendmail的过程

### ISSUE THREAD

**Issue by leekaka** [chenjiandongx/email-subscribe#6]
你这里不用写登录名称和密码，
我不知道怎么实现的诶，求指导一下，
我查了用sendmail，不太会用

**Comment by chenjiandongx** [comment]
我放在了环境变量里面了 os.environ.get() 可以获取到

**Comment by leekaka** [comment]
thx,回去试一试，天气接口变了

**Comment by chenjiandongx** [comment]
天气接口不知道哈 现在都是 one 那个了

**Comment by leekaka** [comment]
不好意思再问下哈，这个Travis运行，怎么使用环境变量呢

**Comment by leekaka** [comment]
在travis里运行的时候，会死在运行程序上，请问你遇到过么

**Comment by leekaka** [comment]
![image](https://user-images.githubusercontent.com/29266786/47491633-d4f2e580-d87d-11e8-832a-e0140375248c.png)
请问下你的环境变量也是这样简单写入，还是用了复杂的密钥之类的

**Comment by leekaka** [comment]
不好意思打扰啦，基本上把你的第一版自动发送邮件改了一下

**Comment by leekaka** [comment]
不好意思最后问一下这个环境变量你是怎么设置在travis里的，我尝试了两种方法都不行额

**Comment by leekaka** [comment]
![image](https://user-images.githubusercontent.com/29266786/47612878-d4955d00-dabe-11e8-8424-95a829110fee.png)
这种测试登录的都失败。。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/47613273-0f02f800-dac7-11e8-9932-8817446626a2.png)

这里你有没有配置好

**Comment by leekaka** [comment]
谢谢，我搞定啦，是发送邮件的时候，得用你的SMTP_SSL,而不是SMTP("")

**Comment by chenjiandongx** [comment]
OK
